import {
  SplitSquareHorizontal,
  Type,
  AlignLeft,
  Hash,
  Calendar,
  Clock,
  ChevronDown,
  ListChecks,
  CheckCircle2,
  ToggleLeft,
  UploadCloud,
  PenTool,
  MapPin,
  Mail,
  Phone,
  Star,
  SlidersHorizontal,
  QrCode,
  Palette,
  Link2,
  FileText,
} from "lucide-react";

export const FIELD_TYPES = [
  { id: "section", label: "Sección", icon: SplitSquareHorizontal, color: "text-emerald-400", group: "basicos", inlineEditable: false },
  { id: "text", label: "Texto", icon: Type, color: "text-slate-300", group: "basicos", inlineEditable: true },
  { id: "textarea", label: "Texto Largo", icon: AlignLeft, color: "text-slate-300", group: "basicos", inlineEditable: true },
  { id: "number", label: "Número", icon: Hash, color: "text-emerald-400", group: "basicos", inlineEditable: true },
  { id: "date", label: "Fecha", icon: Calendar, color: "text-amber-400", group: "basicos", inlineEditable: true },
  { id: "time", label: "Hora", icon: Clock, color: "text-rose-400", group: "basicos", inlineEditable: true },
  { id: "selector", label: "Selector", icon: ChevronDown, color: "text-blue-400", group: "seleccion", inlineEditable: false },
  { id: "multiselect", label: "Multi-select", icon: ListChecks, color: "text-indigo-400", group: "seleccion", inlineEditable: false },
  { id: "radio", label: "Radio", icon: CheckCircle2, color: "text-violet-400", group: "seleccion", inlineEditable: false },
  { id: "boolean", label: "Sí / No", icon: ToggleLeft, color: "text-orange-400", group: "seleccion", inlineEditable: false },
  { id: "email", label: "Email", icon: Mail, color: "text-sky-400", group: "avanzados", inlineEditable: true },
  { id: "phone", label: "Teléfono", icon: Phone, color: "text-teal-400", group: "avanzados", inlineEditable: true },
  { id: "image", label: "Imagen", icon: UploadCloud, color: "text-pink-400", group: "avanzados", inlineEditable: false },
  { id: "signature", label: "Firma", icon: PenTool, color: "text-cyan-400", group: "avanzados", inlineEditable: false },
  { id: "gps", label: "GPS", icon: MapPin, color: "text-rose-400", group: "avanzados", inlineEditable: false },
  { id: "rating", label: "Calificación", icon: Star, color: "text-yellow-400", group: "avanzados", inlineEditable: false },
  { id: "slider", label: "Slider", icon: SlidersHorizontal, color: "text-lime-400", group: "avanzados", inlineEditable: false },
  { id: "file", label: "Archivo adjunto", icon: UploadCloud, color: "text-emerald-300", group: "personalizados", inlineEditable: false },
  { id: "barcode", label: "Código QR / Barras", icon: QrCode, color: "text-orange-300", group: "personalizados", inlineEditable: true },
  { id: "color", label: "Color", icon: Palette, color: "text-fuchsia-400", group: "personalizados", inlineEditable: false },
  { id: "url", label: "URL / Enlace", icon: Link2, color: "text-blue-300", group: "personalizados", inlineEditable: true },
  { id: "readonly_text", label: "Campo readonly", icon: FileText, color: "text-slate-400", group: "personalizados", inlineEditable: true },
];
