name: Deploy to Firebase Hosting on PR and Push
'on':
  push:
    branches:
      - main
  pull_request:
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FORMAFLOW_CENTRAL_CDBAA }}'
          channelId: live
          projectId: formaflow-central-cdbaa
